### ISSUE TITLE
add more to website to the nsfw commands

### ISSUE THREAD

**Issue by CFTheMaster** [YorkAARGH/Okami#26]
i would recommend some big names plus link to
[yande.re](https://yande.re/help/api)
[konachan](http://konachan.com/help/api)
[danbooru](http://danbooru.donmai.us/wiki_pages/43568)
[gelbooru](https://gelbooru.com/index.php?page=help&topic=dapi)
[lolibooru: i recommend for this one not going explicit just rating:questionable because reasons](https://lolibooru.moe/help/api)

**Comment by auguwu** [comment]
cf the hentai is back again everyone xD

**Comment by AndrewJWin** [comment]
For the bottom one, "lolibooru" since of the nature of "loli" I will recommend against using it at all.

Do *any* of them have any APIs @CFTheMaster?

**Comment by CFTheMaster** [comment]
if you click on the names it send it brings you to the api page
most of them just work with http requests
for example you could do: http://konachan.com/post.json?tags={0}&limit={1}&page={2}
most sites are locked with a 100 images per page limit
i recommond using JSON instead of XML some of them user as standard XML for example: gelbooru
it works like this when using gelbooru: http://gelbooru.com/index.php?page=dapi&s=post&q=index&limit={0}&tags={1}&pid={2}&json=1

**Comment by YorkAARGH** [comment]
@AndrewJWin they all have api endpoints, and I'm pretty sure I will avoid the loli one _just in case_

**Comment by auguwu** [comment]
@YorkAARGH you should avoid it since it's aganist TOS! :P

**Comment by YorkAARGH** [comment]
I've added yande.re, konachan and danbooru, gelbooru uses xml, which I'm not happy about

**Comment by YorkAARGH** [comment]
All but loli has been added, and I'm not going to add it, so yeah lol
