### ISSUE TITLE
Command Bug

### ISSUE THREAD

**Issue by Jackthehaxk21** [YorkAARGH/Okami#32]
when using the command 'pay' you must mention someone,
when you do not mention a valid user it says it's not a user but then dialogue comes up to pay 'Misaki' the specified amount

---------------------------------
when using the command 'brain' and supply no args it will stay on a loading loop.
possible fix:
`if (args.length == 0) return message.response(undefined, 'Invalid Command usage: \${this.help.usage}\');`

**Comment by AndrewJWin** [comment]
What steps do you use to recreate your first glitch?

**Comment by Jackthehaxk21** [comment]
York knows but cant find why it’s doing it here’s what you can use,
‘m.pay @hdhshshdgdhdhg 200’ when the mention isn’t a user it pays Misaki

**Comment by AndrewJWin** [comment]
Fixed with [proof](https://andrew-is.online/i/k80n1.png).

**Comment by AndrewJWin** [comment]
Brain is also fixed, but no proof provided.
