### ISSUE TITLE
Canvas commands don't support Unicode

### ISSUE THREAD

**Issue by tech6hutch** [YorkAARGH/Okami#61]
Canvas commands don't display Unicode characters (such as Japanese) correctly.
![image](https://user-images.githubusercontent.com/25398066/36263747-e05e3b7e-1238-11e8-91b5-82fc9c9beac6.png)
![image](https://user-images.githubusercontent.com/25398066/36263770-ed9ccaf8-1238-11e8-96c4-86c180cc923c.png)

Text commands seem to handle Japanese fine:
![image](https://user-images.githubusercontent.com/25398066/36263855-24cceaa8-1239-11e8-9e17-d141c0018d42.png)

**Comment by YorkAARGH** [comment]
This is more an issue for the Idiotic-API than Misaki, I'll pass it along tho.

**Comment by tech6hutch** [comment]
Oh okay, sorry
